spring:
  application:
    name: customers-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888/}

eureka:
  instance:
    preferIpAddress: true
  client:
    service-url:
      defaultZone: ${DISCOVERY_SERVER_URL:http://localhost:8761/eureka}

logging:
  level:
    root: WARN
    org.springframework.samples.petclinic.customers: INFO
    org.springframework.samples.petclinic.customers.web.PetResource: INFO
    org.springframework.samples.petclinic.customers.aws: INFO
  pattern:
    level: trace_id=%mdc{trace_id} span_id=%mdc{span_id} trace_flags=%mdc{trace_flags} %5p

resilience4j:
  circuitbreaker:
    instances:
      pet-service:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10

---
spring:
  config:
    activate:
      on-profile: docker
    import: configserver:http://config-server:8888

---
# Prod profile
spring:
  config:
    activate:
      on-profile: ecs

eureka:
  instance:
    ipAddress: ${CUSTOMER_SERVICE_IP:customer-service}

---
# EC2 profile
spring:
  config:
    activate:
      on-profile: ec2

eureka:
  instance:
    hostName: ${CUSTOMERS_SERVICE_IP:http://customers.demo.local}